### PR TITLE
Sunsetting apps from DVP.

### PR DESCRIPTION
**Pull request by Tay-Sike**
Is this a new product?
No

Has this been deployed successfully from a branch?
Yes

Are load balancer rules being removed or renamed?
Removed.
- VRMS (bridg)
- carma-mpi-bulk
- patsr
- mpi-msg-reciever
- mvi-ent (mpi-e)
- squares

Are ingress definitions being removed or renamed?
Removed.

Are Kubernetes namespaces being removed or renamed?
Removed.

Has DevOps been consulted on resource limits?
N/A.

### Step 3 of Sunsetting remaining non-health applications.

Changes:
- remove products from Jenkins file
- move .yaml and .conf files to the attic/

Step 1 can be found at https://github.com/department-of-veterans-affairs/health-apis-promotatron/pull/110 
Step 2 should be worked by DevOps to collect health checks from DTC Integration Platform.

### CODE REVIEW

**Comment by Tay-Sike** [comment]
Some mock apps remain. Let me know if those should be removed with this process.

**Comment by bschofield-va** [comment]
mocks apps can remain for now

**Review by bschofield-va — APPROVED** [review]

**Review by bschofield-va — CHANGES_REQUESTED** [review]
ingress tests remain and are failing

**Comment by bschofield-va** [comment]
Entries need to be removed https://github.com/department-of-veterans-affairs/health-apis-deployer/blob/qa/ingress.tests#L30

Have you coordinated with DevOps to remove apps from k8s, albs, target groups, etc.

**Comment by Tay-Sike** [comment]
@bschofield-va removed ingress tests for the apps being removed.

**Review by bschofield-va — APPROVED** [review]

**Pull request merged**
