### PR TITLE
Namespace CPU/Memory Limits

### PR DESCRIPTION
**Pull request by mramirez-va**
Enforces CPU/memory limits for each Namespace using ResourceQuota.

**Note:** Any applications deployed under a namespace with quota enforcement will require proper limits set in their respective deployment configurations, per container. The sum of the limits for all containers in a namespace, for CPU or memory, must not exceed the quota CPU or memory limits.

[Here's an example of how we set it for GAL](https://github.com/department-of-veterans-affairs/health-apis-gal-deployment/blob/1d1ced92af528c081f09d91bdc34c998146e8506/deployment.yaml#L33)

### CODE REVIEW

**Comment by mramirez-va** [comment]
FYI - @Tay-Sike

**Comment by dtournour-va** [comment]
So we are going to let namespaces live and die as a whole? 
Assuming a static number of pods for each deployment.  Since it wont scale?

How does that even work?  Can one pod go bad and kill everything in a namespace instead of just killing itself?  Does the namespaces restart all applications if they exceed the memory limits?

The way limits work on individual deployments is they get passed to docker and docker oom kills them and they get a new one launched instantly.  So what does it pass docker if a GROUP of applications share certain limit?

**Comment by mramirez-va** [comment]
@dtournour-va  Good news is we are actively working on integrating horizontal-autoscaling for pods.

The limits set at the namespace is the _sum_ of limits across all containers within that namespace. My understanding of this is that each namespace is given a bucket of CPU/memory and this is divided amongst the containers as desired. So if a namespace "Letters" with a memory quota of 5Gi has a pod A with memory limits of 2Gi and pod B with 3Gi, why would pod A going down also take down pod B?

**Comment by dtournour-va** [comment]
@mramirez-va Explained this to me.  I had a misunderstanding on how the overall namespace limits worked.

**Comment by mramirez-va** [comment]
Closing this and reopening a PR per-product.

**Pull request closed without merging**
