### PR TITLE
Task/shank 175 update rule priorities

### PR DESCRIPTION
**Pull request by jhulbert-va**
# DONT MERGE UNTIL AFTER MEETING WITH TEAM LEADS

This Pull Request refactors the routes configured for the applications in preparation for different applications serving different version of resources.

[SHANK-175](https://vasdvp.atlassian.net/browse/SHANK-175)

[Confluence Page](https://vasdvp.atlassian.net/wiki/spaces/APIMO/pages/995360776/Load+Balancer+Rules+and+Priorities)

Rules can be listed using:
```
$ list-load-balancer-rules
10    /hello*                                  exemplar
20    /hola*                                   exemplar
30    fhir/v0/*/AllergyIntolerance*            data-query
40    fhir/v0/*/Appointment*                   data-query
50    fhir/v0/*/Condition*                     data-query
60    fhir/v0/*/DiagnosticReport*              data-query
70    fhir/v0/*/Encounter*                     data-query
...
```

### CODE REVIEW

**Comment by jhulbert-va** [comment]
> This plus the planned unifier rules will push us over 50%.

@beaugrantham-va I think the

**Comment by jhulbert-va** [comment]
Oops...

**Comment by ilaflamme-va** [comment]
I believe this is the intention of the 10 priority gap, @alecbert-va

**Comment by jhulbert-va** [comment]
> What is the plan for when new resources are introduced? If we suddenly have an UC resource called `AppointmentForCare` or something, we'd obviously need to place it above Appointment currently at priority 40. Does this new resource get priority 40 and we have a waterfall PR for anything beneath or is the idea we can use that 30-40 gap as wiggle room to avoid sweeping PRs for new resources?

In the case of new resources with similar names to other existing resources, my thought is:
1. Pull out the `Appointment` resource from its 40 slot into a slot with a higher priority value
2. Put `AppointmentForCare` in that slot (Assuming it doesnt conflict with anything else)
4. Rebuild data-query so the `Appointment` rule gets moved
5. Build the app that is serving `AppointmentForCare` (it will now be in the 40 slot)

In this way, the slotted approach makes creating a moving rules a lot easier to do. When priority values are as close as they are now, moving rules is a lot harder to do.

**Pull request merged**
